# Array concat and split 

In [1]:
import numpy as np 

In [3]:
arr1=np.arange(1,17).reshape(4,4)

In [4]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
arr2=np.arange(17,33).reshape(4,4)

In [6]:
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [7]:
list1=[2,4,6,8]

In [8]:
list2=[1,8,3,5]

In [9]:
list1+list2

[2, 4, 6, 8, 1, 8, 3, 5]

In [10]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [18]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [19]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [20]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [21]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [22]:
np.vstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [24]:
np.split(arr2,4)

[array([[17, 18, 19, 20]]),
 array([[21, 22, 23, 24]]),
 array([[25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

In [25]:
type(list1)

list

In [26]:
list1[0]

2

In [30]:
type(list1[0])

int

In [31]:
d1=np.array([0,2,4,6,9,4])

In [32]:
d2=np.split(d1,[4,9])

In [33]:
print(d2)

[array([0, 2, 4, 6]), array([9, 4]), array([], dtype=int64)]
