In [2]:
import numpy as np
np.array([1,2,34,5])

array([ 1,  2, 34,  5])

In [3]:
arr_1=np.array([1,2,3,4,5,6])

In [4]:
print(arr_1)

[1 2 3 4 5 6]


In [6]:
type(arr_1)

numpy.ndarray

In [10]:
arr_1.size

6

In [8]:
arr_1.ndim

1

In [11]:
arr_1.shape

(6,)

In [12]:
arr_1.dtype

dtype('int64')

In [17]:
arr_2=np.array([[1,23,3,4,45],[5,6,8,8,9]])

In [18]:
print(arr_2)

[[ 1 23  3  4 45]
 [ 5  6  8  8  9]]


In [20]:
arr_2.size

10

In [21]:
arr_2.shape

(2, 5)

In [22]:
arr_2.ndim


2

In [23]:
import numpy as np
max_1=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [24]:
print(max_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
max_1.ndim

2

In [26]:
max_1.shape

(3, 3)

In [27]:
max_1.size

9

In [31]:
max_2=np.ones(5)

In [32]:
print(max_2)

[1. 1. 1. 1. 1.]


In [33]:
max_2.dtype

dtype('float64')

In [36]:

max_3=np.ones((3,4))

In [37]:
print(max_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
mx_0s=np.zeros((4,6),dtype=int)

In [43]:
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [44]:
mx_0s.dtype

dtype('int64')

In [45]:
em_mx=np.empty((3,3))

In [46]:
print(em_mx)

[[4.67960708e-310 2.01589600e-312 1.29441743e-312]
 [2.37663529e-312 2.35541533e-312 2.10077583e-312]
 [8.48798317e-313 8.70018275e-313 0.00000000e+000]]
