# Random Sampling


In [1]:
import numpy as np

In [2]:
np.random.random(1)

array([0.76813361])

In [3]:
np.random.random((3,3))

array([[0.37190726, 0.65663513, 0.9220329 ],
       [0.6519176 , 0.88484712, 0.53734467],
       [0.69823385, 0.40725335, 0.26326434]])

In [4]:
np.random.randint((4,4))

array([1, 2])

In [5]:
np.random.randint(1,4,(4,4))

array([[2, 2, 1, 1],
       [3, 3, 2, 1],
       [2, 2, 2, 3],
       [1, 2, 1, 3]])

In [6]:
np.random.randint(1,4,(2,4,4))

array([[[2, 3, 1, 1],
        [1, 2, 1, 3],
        [3, 2, 3, 1],
        [2, 2, 2, 2]],

       [[1, 3, 1, 2],
        [1, 2, 3, 1],
        [1, 1, 3, 3],
        [1, 3, 1, 1]]])

In [7]:
np.random.seed(10)

In [8]:
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [9]:
2**32-1

4294967295

In [10]:
2**3

8

In [11]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [12]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [14]:
np.random.randn(3,3)

array([[ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796],
       [-0.59091299,  0.38936304, -0.52699615]])

In [15]:
x=[1,2,3,4]
np.random.choice(x)

1

In [18]:
for i in range(20):
    print(np.random.choice(x))

4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3
4
1


In [19]:
np.random.permutation(x)

array([2, 3, 4, 1])