In [1]:
import numpy as np
#arage
#np.arange(start,end,step)
ar_1=np.arange(1,13)

In [2]:
print(ar_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
ar_even=np.arange(1,13,2)
print(ar_even)

[ 1  3  5  7  9 11]


In [4]:
#linspace
import numpy as np
np.linspace(1,5,25)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ,
       2.66666667, 2.83333333, 3.        , 3.16666667, 3.33333333,
       3.5       , 3.66666667, 3.83333333, 4.        , 4.16666667,
       4.33333333, 4.5       , 4.66666667, 4.83333333, 5.        ])

In [5]:
#reshape
ar_2=ar_even.reshape(2,3)

In [6]:
print(ar_2)



[[ 1  3  5]
 [ 7  9 11]]


In [7]:
ar3=ar_1.reshape(2,3,2)
print(ar3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
#ravel()
ar3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
#flaten
ar3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
#transhape()
ar3.transpose()


array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [11]:
ar3.T

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

# Mathemetical operation using number


In [12]:
import numpy as np

In [13]:
arr1=np.arange(1,13,2)

In [14]:
arr2=np.arange(5,21,3)

In [15]:
print(arr1,arr2)

[ 1  3  5  7  9 11] [ 5  8 11 14 17 20]


In [16]:
arr1+arr2

array([ 6, 11, 16, 21, 26, 31])

In [17]:
np.add(arr1,arr2)

array([ 6, 11, 16, 21, 26, 31])

In [18]:
np.subtract(arr2,arr1)

array([4, 5, 6, 7, 8, 9])

In [19]:
np.divide(arr2,arr1)

array([5.        , 2.66666667, 2.2       , 2.        , 1.88888889,
       1.81818182])

In [20]:
arr1*arr2

array([  5,  24,  55,  98, 153, 220])

In [21]:
arr1@arr2

555

In [22]:
#matrix multiplication
arr1.dot(arr2)

555

In [23]:
#max()
arr1.max()

11

In [24]:
arr1.argmax()

5

In [25]:
#min()
arr1.min()

1

In [26]:
arr1.argmin()

0

In [27]:
#sum()
arr1.sum()

36

In [28]:
#mean()
arr1.mean()

6.0

In [29]:
#squre of each
np.sqrt(arr1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479])

In [30]:
#std()
np.std(arr1)

3.415650255319866

In [31]:
#exp()
np.exp(arr1)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04])

In [32]:
#log()
np.log(arr2)

array([1.60943791, 2.07944154, 2.39789527, 2.63905733, 2.83321334,
       2.99573227])

In [33]:
mx4=np.arange(1,101).reshape(10,10)

In [34]:
print(mx4)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [36]:
mx4[0,0]

1

In [38]:
mx4[9,9]

100

In [41]:
mx4[0,0].ndim

0

In [42]:
mx4[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
mx4[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [44]:
mx4[0,:7]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
mx4[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [46]:
mx4[:,10:0]

array([], shape=(10, 0), dtype=int64)

In [47]:
mx4[:,0:1].ndim

2

In [48]:
mx4[2:8,1:7]

array([[22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77]])

In [49]:
mx4[2:8,1:7].ndim

2

In [52]:
mx4[:,1:7]

array([[ 2,  3,  4,  5,  6,  7],
       [12, 13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37],
       [42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77],
       [82, 83, 84, 85, 86, 87],
       [92, 93, 94, 95, 96, 97]])